# Generated by Django 3.2.3 on 2021-06-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='count_ans1',
            field=models.IntegerField(default=0),
        ),
    ]
