# Generated by Django 3.2.3 on 2021-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_count_ans1'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='count_ans2',
            field=models.IntegerField(default=0),
        ),
    ]
